version: '3.8'

volumes:
  postgres-data:

services:
  app:
    container_name: javadev
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
        # 👇 後述する properties のフォールバック値と完全に一致させる
        POSTGRES_PASSWORD: password
        POSTGRES_USER: postgres
        POSTGRES_DB: mydatabase
        POSTGRES_HOSTNAME: postgresdb

    user: "vscode"
    volumes:
      - ../..:/workspaces:cached
      
    command: sleep infinity

    depends_on:
      db:
        condition: service_healthy
    networks:
      - shared-net # 🌟 フロントと同じ共通ネットワークに所属！

  db:
    container_name: postgresdb
    image: postgres:16
    restart: unless-stopped
    networks:
      - shared-net # 🌟 フロントと同じ共通ネットワークに所属！
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mydatabase

networks:
  # 🌟 事前にホスト側で作成した共通ネットワークを外部参照する
  shared-net:
    external: true